"""create users, events_normalized, detections

Revision ID: 594f8da223c6
Revises: 
Create Date: 2025-08-26 17:31:05.210062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594f8da223c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.String(length=2048), nullable=True),
    sa.Column('event_ids', sa.JSON(), nullable=True),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assignee', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detections'))
    )
    op.create_index(op.f('ix_detections_kind'), 'detections', ['kind'], unique=False)
    op.create_index(op.f('ix_detections_rule_id'), 'detections', ['rule_id'], unique=False)
    op.create_index(op.f('ix_detections_severity'), 'detections', ['severity'], unique=False)
    op.create_index(op.f('ix_detections_status'), 'detections', ['status'], unique=False)
    op.create_table('events_normalized',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_module', sa.String(length=64), nullable=False),
    sa.Column('event_action', sa.String(length=64), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=True),
    sa.Column('dst_ip', sa.String(length=45), nullable=True),
    sa.Column('user', sa.String(length=128), nullable=True),
    sa.Column('http_method', sa.String(length=16), nullable=True),
    sa.Column('http_path', sa.String(length=512), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('fields_json', sa.JSON(), nullable=True),
    sa.Column('raw_ref', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events_normalized'))
    )
    op.create_index(op.f('ix_events_normalized_dst_ip'), 'events_normalized', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_events_normalized_event_action'), 'events_normalized', ['event_action'], unique=False)
    op.create_index(op.f('ix_events_normalized_event_module'), 'events_normalized', ['event_module'], unique=False)
    op.create_index(op.f('ix_events_normalized_http_path'), 'events_normalized', ['http_path'], unique=False)
    op.create_index(op.f('ix_events_normalized_src_ip'), 'events_normalized', ['src_ip'], unique=False)
    op.create_index(op.f('ix_events_normalized_timestamp'), 'events_normalized', ['timestamp'], unique=False)
    op.create_index(op.f('ix_events_normalized_user'), 'events_normalized', ['user'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_events_normalized_user'), table_name='events_normalized')
    op.drop_index(op.f('ix_events_normalized_timestamp'), table_name='events_normalized')
    op.drop_index(op.f('ix_events_normalized_src_ip'), table_name='events_normalized')
    op.drop_index(op.f('ix_events_normalized_http_path'), table_name='events_normalized')
    op.drop_index(op.f('ix_events_normalized_event_module'), table_name='events_normalized')
    op.drop_index(op.f('ix_events_normalized_event_action'), table_name='events_normalized')
    op.drop_index(op.f('ix_events_normalized_dst_ip'), table_name='events_normalized')
    op.drop_table('events_normalized')
    op.drop_index(op.f('ix_detections_status'), table_name='detections')
    op.drop_index(op.f('ix_detections_severity'), table_name='detections')
    op.drop_index(op.f('ix_detections_rule_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_kind'), table_name='detections')
    op.drop_table('detections')
    # ### end Alembic commands ###
