"""add block_rules table

Revision ID: 905ebe8e961e
Revises: 139d69ca44ae
Create Date: 2025-08-27 19:50:34.649770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905ebe8e961e'
down_revision: Union[str, None] = '139d69ca44ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_block_rules'))
    )
    op.create_index(op.f('ix_block_rules_active'), 'block_rules', ['active'], unique=False)
    op.create_index(op.f('ix_block_rules_ip'), 'block_rules', ['ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_block_rules_ip'), table_name='block_rules')
    op.drop_index(op.f('ix_block_rules_active'), table_name='block_rules')
    op.drop_table('block_rules')
    # ### end Alembic commands ###
